
package com.syx.weather_annotaion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherInterfaceImpl", targetNamespace = "http://weather.syx.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherInterfaceImpl {


    /**
     * 
     * @param cityname
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getweather", targetNamespace = "http://weather.syx.com", className = "Getweather")
    @ResponseWrapper(localName = "getweatherResponse", targetNamespace = "http://weather.syx.com", className = "GetweatherResponse")
    @Action(input = "http://weather.syx.com/WeatherInterfaceImpl/getweatherRequest", output = "http://weather.syx.com/WeatherInterfaceImpl/getweatherResponse")
    public String getweather(
        @WebParam(name = "cityname", targetNamespace = "")
        String cityname);

}
